# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'areaInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(310, 400))
        MainWindow.setMaximumSize(QtCore.QSize(310, 400))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shapeLabel = QtWidgets.QLabel(self.centralwidget)
        self.shapeLabel.setGeometry(QtCore.QRect(90, 10, 130, 20))
        self.shapeLabel.setObjectName("shapeLabel")
        self.baseLabel = QtWidgets.QLabel(self.centralwidget)
        self.baseLabel.setGeometry(QtCore.QRect(40, 82, 210, 20))
        self.baseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.baseLabel.setObjectName("baseLabel")
        self.shapeSelect = QtWidgets.QComboBox(self.centralwidget)
        self.shapeSelect.setGeometry(QtCore.QRect(120, 30, 70, 30))
        self.shapeSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shapeSelect.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.shapeSelect.setObjectName("shapeSelect")
        self.shapeSelect.addItem("")
        self.shapeSelect.addItem("")
        self.shapeSelect.addItem("")
        self.shapeSelect.addItem("")
        self.shapeSelect.addItem("")
        self.baseInput = QtWidgets.QLineEdit(self.centralwidget)
        self.baseInput.setGeometry(QtCore.QRect(120, 102, 70, 30))
        self.baseInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.baseInput.setText("")
        self.baseInput.setAlignment(QtCore.Qt.AlignCenter)
        self.baseInput.setObjectName("baseInput")
        self.heightLabel = QtWidgets.QLabel(self.centralwidget)
        self.heightLabel.setGeometry(QtCore.QRect(40, 154, 220, 20))
        self.heightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.heightLabel.setObjectName("heightLabel")
        self.heightInput = QtWidgets.QLineEdit(self.centralwidget)
        self.heightInput.setGeometry(QtCore.QRect(120, 174, 70, 30))
        self.heightInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.heightInput.setText("")
        self.heightInput.setAlignment(QtCore.Qt.AlignCenter)
        self.heightInput.setObjectName("heightInput")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(135, 298, 40, 20))
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(120, 239, 70, 30))
        self.submitButton.setObjectName("submitButton")
        self.resultBox = QtWidgets.QTextEdit(self.centralwidget)
        self.resultBox.setGeometry(QtCore.QRect(90, 318, 130, 25))
        self.resultBox.setReadOnly(True)
        self.resultBox.setObjectName("resultBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 310, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Areas of Shapes"))
        self.shapeLabel.setText(_translate("MainWindow", "What shape do you have?"))
        self.baseLabel.setText(_translate("MainWindow", "What is the value of the base (or radius)?"))
        self.shapeSelect.setItemText(0, _translate("MainWindow", "Select"))
        self.shapeSelect.setItemText(1, _translate("MainWindow", "Circle"))
        self.shapeSelect.setItemText(2, _translate("MainWindow", "Square"))
        self.shapeSelect.setItemText(3, _translate("MainWindow", "Rectangle"))
        self.shapeSelect.setItemText(4, _translate("MainWindow", "Triangle"))
        self.heightLabel.setText(_translate("MainWindow", "What is the value of the height? (if needed)"))
        self.resultLabel.setText(_translate("MainWindow", "Result:"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.resultBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Result Displays Here</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
